### ISSUE TITLE
Time data cannot calculate difference

### ISSUE THREAD

**Issue by abstaincr** [bedatadriven/renjin#101]
Given 2 characters of date, for example: (all codes in R)
```r
t1 <- "Tue Feb 17 10:30:00 2015"
t2 <- "Tue Feb 17 16:20:24 2015"
```
And change the data type to date:
```r
tt1 <- strptime(t1, "%a %b %d %H:%M:%S %Y")
tt2 <- strptime(t2, "%a %b %d %H:%M:%S %Y")
```
Calculate the time difference:
```r
td <- tt2 - tt1
```
If in GNU R, the result is "Time difference of 5.84 hours"

But in Renjin, the result is "Time difference of -10 mins"

**Comment by mjkallen** [comment]
Calculating the difference like in your example is the same as doing
```r
`-.POSIXt`(tt2, tt1)
```
That is: the `-.POSIXt` function is called. In this example, this function passes the work on to the `difftime()` function which is just a pure R function in base R. So this is not where the problems is.

The issue is caused earlier by the incorrect conversion from the datetime string to a POSIXlt object with `strptime()`. I have opened a new issue to address this. Thanks for reporting!
