### ISSUE TITLE
file() does not support URLs

### ISSUE THREAD

**Issue by econ-r** [bedatadriven/renjin#163]
The following works in GNU R but not Renjin: 
`read.csv("http://ichart.finance.yahoo.com/table.csv?s=SPY&a=0&b=01&c=2007&d=3&e=29&f=2016&g=d&q=q&y=0&z=SPY&x=.csv")`

**Comment by akbertram** [comment]
Looks like this is something that `file()` is supposed to handle, which is what `read.csv` calls under the hood.

**Comment by econ-r** [comment]
file() does support some urls for example `read.table("http://www.ats.ucla.edu/stat/examples/ara/angell.txt")` works. Seemed to me yesterday that everything after the `?` in the url string was dropped? I do not have my development laptop to be able to tell you the exact error unfortunately.

**Comment by akbertram** [comment]
It looks like both the URLs are handled correctly by `url()`, the problem seems to be that `file()` doesn't check for a URL-like argument and tries to open via the sessions' virtual file system, whose support for URLs is probably not very good.

I think that if our implementation of `file()` checks for an "http:" or "https:" prefix and then diverts to `url()` it should just work.

**Comment by psolaimani** [comment]
issue fixed.

**Comment by econ-r** [comment]
You guys are amazing!

**Comment by akbertram** [comment]
@econ-r You've caught us in a package-fixing frenzy :-)

**Comment by econ-r** [comment]
You might want to take a look at download.file(), it has some unexpected
behaviour with wget and is used in quite a few packages.
