### ISSUE TITLE
Implement chol()

### ISSUE THREAD

**Issue by uwer** [bedatadriven/renjin#169]
tested in
renjin-studio-0.8.2005-jar-with-dependencies.jar

and 
renjin-script-engine-0.8.1931-jar-with-dependencies.jar

using 
mvtnorm-1.0-5-b17.jar

dmvnorm(x=c(0,0), mean=c(1,2)) 
produces
[1] 0

should be  
 [1] 0.05854983

Looking at tests on 
http://packages.renjin.org/package/org.renjin.cran/mvtnorm
under Mvnorm-examples
fails too
previously successful and correct

Please advise a last good combination of releases, I need to deploy tomorrow ...

**Comment by mjkallen** [comment]
Sorry @uwer, we're on holiday at the moment! But we will have a look as soon as we can.

**Comment by uwer** [comment]
Hi Marteen,

Thanks for getting back to me so quickly -
I have gone back in versions till I found one which was at least for what i
need now correct (0.9991).

BTW, all tests on thar package and others fail and gave failed for a while
- I ma surprised nobody picked that up.

Cheers
Uwe





On Mon, May 9, 2016 at 3:17 AM, Maarten-Jan Kallen <notifications@github.com

**Comment by akbertram** [comment]
Looking at the [history of the Mvnorm-examples test](http://packages.renjin.org/package/org.renjin.cran/mvtnorm/1.0-5/test/Mvnorm-examples/history), it looks like at least on mvtnorm-1.0-5, this has always been a problem because the function `dmvnorm` relies on the function `dchol`, which in turn invokes a function 'dchdc' from the `appl` library that we hadn't included in Renjin. 

Normally, this would result in an error and not the value `0`, but `dmvnorm` wraps the call to `dchol` in a `tryCatch` call, probably to trap out of bounds errors or something. Unfortunately, this is mistaken for an out of bounds error and `dmvnorm` returns zero.

**Comment by uwer** [comment]
Thanks Alex,

needless to say, it be great if that was pointed out somewhere

Where can i get that library?


Cheers

Uwe

**Comment by akbertram** [comment]
@uwer , the `appl` library is actually part of GNU R, and is included in Renjin's build as well. The problem was that, originally, not all of the library could be included in Renjin because of some problems with our Fortran to JVM bytecode compiler. Since then, our compiler has improved, and I was able to include all remaining Fortran sources from `appl` in 805e4cb40c942d0299f343784aa1abf1e8125294.

However, it looks like I misdiagnosed the problem: `chol` does not actually depend on `appl`, though other parts of `mvtnorm` do. 

The minimal test case here is actually:

```
chol(diag(1))
```
which fails because of the missing `La_chol` function, which is a wrapper around the lapack function, and has not yet been ported from C to Java. 

GNU R's implementation of the wrapper is in [lapack.c](https://github.com/wch/r-source/blob/trunk/src/modules/lapack/Lapack.c#L921). We use netlib-java for the actual lapack implementation.

**Comment by uwer** [comment]
Thanks Alex,

I will look at the commit, thanks heaps for looking at it this in detail.
If i understand you correctly the latest snapshot will include your
additions and address issues against appl?
If i want to use functions backed by lapack i need to make available lapack
and netlib-java - anyting else?
The documentation on the integration of native libaries is a little sparse.

I did read your recent GCC-Bridge comments and it sounds very interesting.

(I am working with ocean models and data assimilation, lots of Fortran,
some tools would be very handy to have in a platform independent lib..)


Cheers
Uwe

**Comment by akbertram** [comment]
Implemented by 711b5d8bab5ffe5072152d620602da7c9bd15ac9
