### ISSUE TITLE
Relicense under GPL v2

### ISSUE THREAD

**Issue by tninja** [bedatadriven/renjin#239]
GPLv3 is more restrict than v2 and industrial people don't like v3 much.  Usually in industry, v3 is prohibited, and v2 is on the boundary, kind of OK.

If Renjin can be relicensed under GPL v2, we can use it in production.

Thanks in advance!

**Comment by akbertram** [comment]
This would harmonize Renjin's Licensing with GNU R, so I think we would be fine with this at bedatadriven. When I started the Renjin project, I believe the only rational behind GPL v3 was that it was the "latest" version of the GPL in the Google Code License dropdown. 

I would propose changing the license to GPL 2 | GPL 3 so that users can choose the license that fits them best.

We do however need permission from all external contributors. This includes:

@acaloiaro
@billy1380
@cwlaird3
@hannesmuehleisen
@hlin09
@hwvenancio
@jbytecode
@jiessie
@jukiewiczm
@mwprog
@peter-gergely-horvath
@rssh

Can each of you comment here on this issue if you agree? (As well as if I've missed anyone in combing through `git-log`)

**Comment by hannesmuehleisen** [comment]
agree

**Comment by billy1380** [comment]
got mine

**Comment by mjkallen** [comment]
👍

**Comment by peter-gergely-horvath** [comment]
Hi All,

I agree as well.

Cheers,
Peter

2016-09-06 15:11 GMT+02:00 Maarten-Jan Kallen <notifications@github.com>:

**Comment by cwlaird3** [comment]
agree

**Comment by jukiewiczm** [comment]
I agree.

2016-09-06 15:07 GMT+02:00 Alex Bertram <notifications@github.com>:

**Comment by hwvenancio** [comment]
I agree

**Comment by jiessie** [comment]
I agree.

**Comment by mwprog** [comment]
I agree

**Comment by acaloiaro** [comment]
I agree

**Comment by hlin09** [comment]
Agree.

**Comment by rssh** [comment]
agree

**Comment by jbytecode** [comment]
I agree.

**Comment by akbertram** [comment]
By my count, that's everybody! Thanks for the response, and above all, thanks for your contributions to Renjin! After we get back from the meetup in Munich next week, I'll do a final check of the licenses of our dependencies and then start updating license files and document towards the end of the month.

**Comment by acaloiaro** [comment]
If there is any need for my consent in the future, consider mine perpetual
and without limitation. I'm confident you'll continue stewarding the
project responsibly, Alex. Cheers.

**Comment by akbertram** [comment]
Renjin 0.8.2222 is the first build licensed under GPL v2!

Many thanks to you all for the response, and of course, for the contributions to Renjin in the first place!

**Comment by tninja** [comment]
Thanks everyone to make renjin available under GPL v2! Appreciate.
