### ISSUE TITLE
terms(x, 'term.labels') should return deparsed value

### ISSUE THREAD

**Issue by psolaimani** [bedatadriven/renjin#280]
In renjin-benchmarks (RB), survival_simple benchmark fails due to `terms` function not returning deparsed value of `term.labels`

> ERROR: undefined columns selected
>   at stop()
>   at [.data.frame()
>   at strata()
>   at survdiff()
>   at do.analyse()
>   at eval.with.vis()
>   at source()
>   at system.time()

this is caused because in Renjin:
```
z <- terms(data$z1 ~ data$z1, "strata")
attr(z, "term.labels")
```
> [1] "$(data, z1)"

while in GNU R:
```
z <- terms(dt$z1 ~ dt$z1, "strata")
attr(z, "term.labels")
```
> [1] "dt$z1"

minimal test case:
```
library(hamcrest)
z <- terms(dt:z1 ~ dt:z1, "strata")
y <- attr(z, "term.labels")
assertThat(y, equalTo("dt$z1"))
```

**Comment by akbertram** [comment]
@psolaimani somewhere `toString()` is being used instead of `deparse()` which correctly handles binary infix operators. (Try: `deparse(quote(x$y))`)

Maybe here?
https://github.com/bedatadriven/renjin/blob/6089bb33fd70e56e4f15bfbf645814c25b968ca8/core/src/main/java/org/renjin/stats/internals/models/Term.java#L85-L85

**Comment by akbertram** [comment]
@psolaimani seems like this is a quick fix, did you run into any blockers?
