### ISSUE TITLE
Getting error while using RQuantLib package 

### ISSUE THREAD

**Issue by karthiktcs031013** [bedatadriven/renjin#293]
Hi All,

I am new to Renjin, we are currently using R Scripts for statistical calculation and want to integrate this with Java.  So I came across Renjin.  In one of the R Script we are using RQuantLib.  So corresponding RQunatLib pacakage I have used in my Pom.xml

  <dependency>
    <groupId>org.renjin.cran</groupId>
    <artifactId>RQuantLib</artifactId>
    <version>0.4.2-b30</version>
  </dependency>

But While executing I am getting below error:

org.renjin.eval.EvalException: error in load action .__A__.1 for package RQuantLib: NULL: Could not load JVM class 'org.renjin.cran.RQuantLib.RQuantLib' from package 'org.renjin.cran.RQuantLib.RQuantLib'

Could you help me to resolve this.  Whether I am using correct package.
Thank you very much.

Thanks & Regards,
Karthik B

**Comment by akbertram** [comment]
This error message indicates that the compiled C/C++/Fortran code from the RQuantLib package could not be loaded. As indicated by the package [status page](http://packages.renjin.org/package/org.renjin.cran/RQuantLib), this is because our C-to-JVM compiler failed to compile this code.

If you take a look at the [build log](http://packages.renjin.org/package/org.renjin.cran/RQuantLib/0.4.2/build/30) linked to from the status page, you can see that the compilation failed during configuration:

```
checking for quantlib-config... no
configure: error: Please install QuantLib before trying to build RQuantLib.
```
Unfortunately, at this time, we are not ready to support packages with external dependencies in our build system. This might change in the future but probably not in the short term.
