### ISSUE TITLE
Memory Usage Statistics

### ISSUE THREAD

**Issue by DaveJarvis** [bedatadriven/renjin#300]
An informational report using the [Eclipse Memory Analyzer](http://www.eclipse.org/mat/) v1.6.1.

# Overview

![objects-by-size](https://cloud.githubusercontent.com/assets/2131950/22452721/19c72542-e72e-11e6-94ef-bd88e769b130.png)

# Implementation

The `InlineRProcessor` declares three constants, but only one is of any consequence:

```
  private static final ScriptEngine ENGINE =
    (new ScriptEngineManager()).getEngineByName( "Renjin" );
```

# Default Report

> The class "com.scrivenvar.processors.InlineRProcessor", loaded by
> "sun.misc.Launcher$AppClassLoader @ 0x5c9404088", occupies 8,487,344 (26.16%) bytes. The 
> memory is accumulated in one instance of "org.renjin.eval.Context" loaded by 
> "sun.misc.Launcher$AppClassLoader @ 0x5c9404088".
> 
> Keywords
> org.renjin.eval.Context
> com.scrivenvar.processors.InlineRProcessor
> sun.misc.Launcher$AppClassLoader @ 0x5c9404088

![shortest-path](https://cloud.githubusercontent.com/assets/2131950/22452803/d7793d0a-e72e-11e6-9018-4aa7ca770c30.png)

# Histogram

![histogram](https://cloud.githubusercontent.com/assets/2131950/22452853/2b1a51ce-e72f-11e6-8225-84b9b2055f7e.png)

# Objects

![objects-01](https://cloud.githubusercontent.com/assets/2131950/22452883/74d5c7ee-e72f-11e6-8df6-845bf60c7996.png)

# Expanded Objects

![objects-expanded](https://cloud.githubusercontent.com/assets/2131950/22452906/9198fbbc-e72f-11e6-867b-356ac04e1cdb.png)

**Comment by akbertram** [comment]
Thanks for this, is there anything that look suspect or should be reduced as far as memory usage goes?

**Comment by akbertram** [comment]
PairList.Nodes instances are created for each element in an R "pairlist" which are linked lists used to store the argument lists of function declaration and during function call argument matching. I'm guessing that due to their relatively small footprint (~6 megabytes?) there are a lot that linger on the heap because there might not be much pressure to garbage collect.

I'm going to close this issue for now, but if you can submit a complete benchmark than we can look concretely at the best strategy for reducing memory usage.
