### ISSUE TITLE
Request to explore JavaCPP as an extension to model RCpp

### ISSUE THREAD

**Issue by abhi18av** [bedatadriven/renjin#329]
Hi dedatadriven team:)

I've been exploring the use case for renjin more and more and I do find that there is tremendous potential in the project - for my own use too. Thanks a lot for this :)

However, as is already known, not many native packages work on Renjin. I know that there have been efforts towards this direction. Still I'd like to suggest that perhaps, https://github.com/bytedeco/javacpp might be a worthy option to explore in this space as well.

It's being used by ND4J and DeepLearning4J projects plus there are a number of bindings already generated located here https://github.com/bytedeco/javacpp-presets .

I hope that JavaCpp might take us closer to a proper package compatibility.

I'm looking forward to this project , Thanks again :)

**Comment by akbertram** [comment]
Thanks for sharing the link! I wasn't aware of the JavaCPP project. 

However - if I understand correctly JavaCPP is only a set of tooling on top of JNI to avoid some of the boilerplate when implementing Java "native" methods.

The choice between JNI and GCC-Bridge for handling native code is a complex one, but the hardest aspect is the bi-directional nature of integration between the R interpreter and the native code in R packages.

It wouldn't do any good to use Javacpp, for example, to call Rcpp code, because the Rcpp code also expects to call hundreds of API functions in the interpreter. We implement (most of) these functions in the [gnur-runtime](https://github.com/bedatadriven/renjin/blob/master/tools/gnur-runtime/src/main/java/org/renjin/gnur/api/Rinternals.java) module, but we also rely on our GCC-Bridge compiler to transform package's native code to work huge differences between Renjin and the GNU R implementation.

Just one of these differences is garbage collection. What do you do when native code allocates memory and then passes it back to the R Interpreter? Renjin's GCC-Bridge will actually maps these allocations to "normal" JVM bytecode so that calls to malloc() are simply normal Java array allocations that can participate in garbage collection. With JNI, these types of movements between the JVM and native code become far, far more complex.

As you mention, the GCC-Bridge toolchain is not yet complete (though I believe most packages with native code *do* compile correctly, though perhaps not most of the most popular). 

We are planning a next iteration of the compiler in the last quarter of this year to address the remaining problem (#276) and then we should be able to compile all remaining R packages with native code to pure byte code.

That's not to say that javacpp couldn't be useful for writing Renjin-specific wrappers to the libraries you mentioned above, but I'm afraid it's a bit orthogonal to the problem of handling R packages written for GNU R with native code. 

See also [last year's blog post introducing GCC-Bridge](http://www.renjin.org/blog/2016-01-31-introducing-gcc-bridge.html)

**Comment by abhi18av** [comment]
Thanks @akbertram  for such an elaborate answer. I've learned more about the things I must consider while linking to native extensions , also the blog post was really handy. Thanks:)

I'm looking forward to the resolution of issue 276.
