### ISSUE TITLE
Renjin version mismatch (0.92627 and 3.5-beta76)

### ISSUE THREAD

**Issue by AlexKuza** [bedatadriven/renjin#487]
Why is the version **3.5-beta76** downloaded on the download page in the Java Library section, and version **0.9.2627** is downloaded on all other sections (Renjin Studio GUI for all platforms [.jar] and Renjin CLI for Debian / Ubuntu [.deb]).

*By the way, the installation method **"Install via APT" does not work** (the following error is displayed):

```
Err:1 http://packages.renjin.org/repo/apt stable/main i386 renjin all 0.9.2725
  500  Internal Server Error [IP: 64.233.164.121 80]
Err:1 http://packages.renjin.org/repo/apt stable/main i386 renjin all 0.9.2725
  500  Internal Server Error [IP: 64.233.164.121 80]
E: Failed to fetch http://packages.renjin.org/repo/apt/pool/renjin-0.9.2725.deb  500  Internal Server Error [IP: 64.233.164.121 80]
```

**Comment by mjkallen** [comment]
Thanks for bringing our attention to this. Many of these links no longer work due to changes in our artifact repository. I have removed these from our website, except the option to download the latest build in a ZIP archive. We currently do not have the resources to support other options to use or test Renjin.

On a side note: these changes also affect the Gradle build since our artifact repository no longer proxies Maven Central. I have fixed this in commit https://github.com/bedatadriven/renjin/commit/4854b3b2bd0f8ee55807909aa5fcb7a3241144e6.
