### ISSUE TITLE
Installation from APT fails with HTTP 500 error

### ISSUE THREAD

**Issue by nuest** [bedatadriven/renjin#491]
When trying to install Renjin from APT as described here: https://github.com/bedatadriven/renjin/#debian-and-ubuntu I get an error: 

```
E: Failed to fetch http://packages.renjin.org/repo/apt/pool/renjin-0.9.2725.deb  500  Internal Server Error
```

A Dockerfile reproducing the problem is here: https://github.com/nuest/renjin-docker/blob/master/0.9.2725-apt/Dockerfile

Any ideas?

**Comment by akbertram** [comment]
The problem is with our APT server. It's taking a bit longer to get the 3.5 release out, and in the meantime the build system is a bit in flux. I'll see if I can fix this today.

I'm curious though why you're using docker here. If you don't want to install Renjin, you can also use the standalone zip distribution: https://nexus.bedatadriven.com/service/local/artifact/maven/redirect?r=renjin-release&g=org.renjin&a=renjin-generic-package&v=RELEASE&e=zip

You can unpack to a local directory and run. It's only dependency is JDK8+, which you likely have available on your system path.

**Comment by nuest** [comment]
I was not aware of the generic package! I think that might also be an effective way for me to build the Docker container. ~~Will give that a try!~~ That works well! Thanks!

Re. why use Docker: It's a good way to package Renjin together with it's dependencies and have a portable app (e.g. in cases where JDK is unlikely to be available).

More background: A student of mine is currently working on a comparison of the geospatial software stack in different R implementations, related to that is #490. There we have a bunch of R implementations and Linux distributions, and those are separated in different Docker images. So, it's not only "I don't want to install", but we need a reproducible documentation of how the environment was created. _Hope this clarifies!_

**Closing the issue, binary installation works for me.**
