### ISSUE TITLE
Could not resolve native method 'lpslink' in package 'lpSolve'

### ISSUE THREAD

**Issue by francescoamato** [bedatadriven/renjin#510]
Hi,
I'm using the package  lpSolve 5.6.13-b14, but I have the error:

java.lang.RuntimeException: org.renjin.eval.EvalException: Could not resolve native method 'lpslink' in package 'lpSolve'

Any idea how to fix this?

Thanks

**Comment by mauroIstat** [comment]
Hi to veryone,

I have the same problem with  lpSolve.

Any idea on how to fix the problem?

Best

**Comment by akbertram** [comment]
This R package is actually a wrapper around a native library called Lp_solve, and uses C code to load a shared library at runtime.

Renjin has a tool chain that can compile C code to Java byte code so that R packages that use C/C++/Fortran can be used as a pure-Java library, but loading a native library at runtime is unfortunately way beyond its capabilities. Renjin is unlikely to ever support this kind of package "out of the box".

I did see that Lp_Solve has a Java wrapper:
http://lpsolve.sourceforge.net/5.5/Java/README.html

The best strategy would probably to use this library from Renjin.

To translate the example from their page would look like something like this in Renjin: (not tested)

```.R
import(lpsolve.LpSolve)

solver <- LpSolve$makeLp(0, 4)

# add constraints
solver$strAddConstraint("3 2 2 1", LpSolve$LE, 4)
solver$strAddConstraint("0 4 3 1", LpSolve$GE, 3)

# set objective function
solver$strSetObjFn("2 3 -2 3");

# solve the problem
solver.solve()

# print solution
print(solver$objective)

var <- solver$getPtrVariables()
print(var)

# delete the problem and free memory
solver$deleteLp()
```

**Comment by mauroIstat** [comment]
@akbertram thank you for your prompt response 👍 

We will try to follow your suggestion,

Mauro
