### ISSUE TITLE
Repackage asm and guava to avoid version conflicts

### ISSUE THREAD

**Issue by jingz8804** [bedatadriven/renjin#63]
Just moving my github question here:
http://stackoverflow.com/questions/24291540/renjin-incompatible-with-grails-application-and-how-are-asm-and-cglib-library-us/24303167#24303167

- Platform: Windows 7
- Grails version for the application: Grails 2.2.3
- Renjin version: 0.7.0-RC7

On application start up, we have the following error message:
```
BeanCreationException: Error creating bean with name 'appService': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: net/sf/cglib/core/DebuggingClassWriter
```
Top result in Google search is probably the only relevant post: NoClassDefFoundError in Grails app using XWiki with Markdown syntax

It indicates there is a jar file conflict between Grails cglib-2.2/asm-3.1 and the other jar you put in the classpath. In my case, the Renjin jar file I assume.

Since Renjin is using asm, is there anyway we can repackage the library and avoid this conflict?

**Comment by akbertram** [comment]
ASM has been repackaged for Renjin in 6807bfe1199f4b6c517967fcc42e2d4eb2f445ea.

With regards to Guava, several Guava interfaces are currently used in Renjin's semi-public API 
(the [Package](https://github.com/bedatadriven/renjin/blob/64dad76c60a14af87e624d23f257d99580966c5b/core/src/main/java/org/renjin/primitives/packaging/Package.java) interface, for example) so repakaging this library would be problematic. We have, however, removed uses of methods from newer Guava releases (ef164a88cee725975e41cdce3f1c06e5d852cac7, for example) so that having an older version of Guava on the classpath will not cause linking errors.

It's certainly still possible to repackage Guava, but I would prefer to avoid this unless there remain significant outstanding problems. So: I will close this issue, and leave it to others to re-open if you disagree!

**Comment by tninja** [comment]
We are trying to use renjin on top of spark so that it can be used distributed and met the guava problem (spark use version 14.0 and renjin depend on 17.0).  A couple of other people hope to have it too: http://www.gitterforum.com/discussion/andypetrella-spark-notebook?page=440

It would be super awesome if we can have guava repackaged.

**Comment by akbertram** [comment]
*sigh* I had hoped to avoid this by avoiding features from new versions of Guava, but it sounds like this is a just a problem that won't go away.

Should be able to finish this in the next week or two, but happy to merge any pull requests for this sooner if submitted.
