### ISSUE TITLE
as.numeric not working as expected

### ISSUE THREAD

**Issue by andytompkins** [bedatadriven/renjin#71]
In R I can write as.numeric("1/2") and the result is NA.
In renjin, the same thing returns 1.
I would offer to patch it, but I do not understand the code base well enough yet to even know where that is implemented :)

**Comment by akbertram** [comment]
The conversion is done by [StringVector.getElementAsDouble()](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/sexp/StringVector.java#L54-54), which in turn relies on [NumericLiterals.parseDouble()](https://github.com/bedatadriven/renjin/blob/master/core/src/main/java/org/renjin/parser/NumericLiterals.java#L75-75).

I believe the problem is the lexer also uses this method and just wants to parse up to the end of a number from among the string of characters.  In the case of `getElementAsDouble()`, we want to instead return NA if we reach the end of the number before the end of the String.

Not sure if `parseDouble` could be adapted or should be split into a different implementation but should be straight foward to fix either way, can I ask you to take a stab at a patch and pull request?

**Comment by akbertram** [comment]
@Artjom-Metro This might be an interesting issue to pick up -- I think it has a reasonably large impact but comes down to a relatively simply fix to the parsing routine.
