### ISSUE TITLE
round() does not accept all GNU R parameter types

### ISSUE THREAD

**Issue by acaloiaro** [bedatadriven/renjin#94]
The following code will fail in Renjin, but succeed in GNU R:
`round(list(1.9853, 2.2837), digits = 2)`

The error is:
> org.renjin.eval.EvalException: Invalid argument:
> round(list, double)
> Expected:
> round(double)
> round(double, integer)
> round(Complex, integer)

I presume `(Complex, integer)` was intended to match this scenario, but it appears to fail. Furthermore, note that the "Invalid Arguments" are listed as `(list, double)` and not `(list, integer)`, which suggests that the literal parameter "2" is being converted to `double`. This aspect of the problem is likely unrelated to `round()`, but a general problem with marshaling literal integer parameters from R to Java. A solution to this problem will need to be well-tested for unintended consequences. 

I have also tested the following line that similarly fails: 
`round(list(1.9853, 2.2837), digits = as.integer(2))`

This correctly reports the parameters `(list, integer)` as expected, but fails on the `list` parameter.

**Comment by mjkallen** [comment]
According to its documentation, the `round(x, digits = 0)` function should accept only *numeric* vectors (and complex vectors) for `x`, not lists. Therefore the error in Renjin is correct. If I try the same command in GNU R, I also get an error:

```
Error in round(list(1.9853, 2.2837), digits = 2) : 
  non-numeric argument to mathematical function
```

The `digits` argument is therefore not the issue here and, for example, `round(1.2345, digits = 2)` results in 1.23 as it should.
